Alteração de configurações, criação das rotas, adição das paginas res…
wiliafsilva/Projeto-ERP pull request #9
Opened 2024-10-30 12:50 UTC by wiliafsilva

2024-10-30 13:08 UTC, RichardSouzza approved these changes

2024-10-30 13:21 UTC, RichardSouzza requested changes

2024-10-30 13:21 UTC, RichardSouzza commented on front-end/src/app/addProdutos/page.tsx
Precisa corrigir responsividade, há um espaço entre o formulário e o rodapé.

![image](https://github.com/user-attachments/assets/789e1261-f4ad-4099-819a-7d8812758d84)

2024-10-30 13:32 UTC, wiliafsilva commented on front-end/src/app/addProdutos/page.tsx
certo, não tinha observado isso.

2024-10-31 10:36 UTC, RichardSouzza commented on front-end/src/app/editarProdutos/page.tsx
Esta página também está com problemas de responsividade.

![image](https://github.com/user-attachments/assets/a9957334-2f40-4864-af31-387c5a18e1b1)

2024-10-31 10:41 UTC, RichardSouzza approved these changes

2024-10-31 10:41 UTC, merged